name: hlsd
description: HLS(.m3u8 files) downloader.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^2.7.1
  http: ^0.12.1
  path: ^1.6.0
  # chewie: ^0.9.10
  provider: ^4.1.3
  pedantic: ^1.8.0
  typeweight: ^1.0.0
  google_fonts: ^1.1.0
  video_player: ^0.10.11+1
  moor_flutter: ^3.0.0
  path_provider: ^1.6.9
  flutter_hls_parser: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  moor_generator: ^3.1.0

flutter:
  uses-material-design: true

scripts: derry.yaml
