name: hlsd
description: HLS(.m3u8 files) downloader.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^2.7.1
  http: ^0.12.1
  path: ^1.6.0
  hive: ^1.4.1+1
  chewie: ^0.9.10
  pedantic: ^1.8.0
  typeweight: ^0.0.2
  hive_flutter: ^0.3.0+2
  google_fonts: ^1.1.0
  video_player: ^0.10.11+1
  path_provider: ^1.6.9
  flutter_hls_parser: ^1.0.0

dependency_overrides:
  dartx: ^0.3.0 # needed for hive to work correctly

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  hive_generator: ^0.7.0+2

flutter:
  uses-material-design: true
